### ISSUE TITLE
[SUGGESTION] Better Quoter

### ISSUE THREAD

**Issue by Yu-Vitaqua-fer-Chronos** [ItzOnlyAnimal/AliuPlugins#1]
Heya, is it possible for you to make it so Quoter just appends the message you're quoting to the position of the cursor? Because that would be a lot nicer, also maybe make it so you can customise if it adds the mention at the end of the message? Because i always delete it and it gets irritating to do it all the time

**Comment by nyakowint** [comment]
Sure, why not. i'll get to it soonish

**Comment by Yu-Vitaqua-fer-Chronos** [comment]
Thanks!

**Comment by nyakowint** [comment]
Heya, in the newest update the mention can be add/removed with a toggle in the plugin settings.
As well as whether or not to append the quote to the end of the message, or just replace the textbox (previous behavior)

**Comment by Yu-Vitaqua-fer-Chronos** [comment]
Thanka for letting me know!
