### ISSUE TITLE
what is "hop on bloons when"

### ISSUE THREAD

**Issue by HumanityI** [ItzOnlyAnimal/AliuPlugins#12]
What is this feature? - Hop on bloons when
"Makes you actually hop on bloons when people say the magic word
Disclaimer: Only works with Bloons TD 6"
I have BTD6 installed but what am supposed to do with it?

**Comment by Vendicated** [comment]
hop on bloons when

**Comment by nyakowint** [comment]
hop on bloons when (this is the keyword)
