### ISSUE TITLE
Fart 

### ISSUE THREAD

**Issue by megacool2325** [ItzOnlyAnimal/AliuPlugins#13]
Fart command works like it pings user when you use optional user ping and send fart like how it would but does not make sound effect like it did before

**Comment by nyakowint** [comment]
eh blame ven <img src="https://cdn.discordapp.com/emojis/940049084696371262.gif">

**Comment by nyakowint** [comment]
[7b23287](https://github.com/ItzOnlyAnimal/AliuPlugins/commit/7b23287b5f5e9d80c1c4cfc32f02277c5a9e6203)
