### ISSUE TITLE
(Timezones) [Bug/Feature Request?] Incorrect time shown in message header

### ISSUE THREAD

**Issue by AAGaming00** [ItzOnlyAnimal/AliuPlugins#17]
The option "Time in message header" currently shows the user's current local time, and can lead to confusion like this:
![Screenshot_20220310-175447.png](https://user-images.githubusercontent.com/42613600/157768775-1fd48e6e-b840-43e7-b1f2-ab3822879d80.png)
I think it would make a lot more sense if it instead showed the user's local time when they sent the message (the message timestamp converted into the user's time zone).

**Comment by nyakowint** [comment]
fixed/added????????? in #35 i think idk
