### ISSUE TITLE
(StatusSheetPlus) Switch account shortcut opens up its setting rather than the switcher

### ISSUE THREAD

**Issue by Uboaaaaa** [ItzOnlyAnimal/AliuPlugins#19]
When both AccountSwitcher and StatusSheetPlus are installed, "SwitchAccount" shortcut appears in th status menu. This shortcut however opens up settings for the plugin AccountSwitcher (where you add / delete account) instead of the actual Switcher (where you switch account). User cannot switch account in the settings menu and therefore have to tap the Switcher icon again to open up the actual switcher.

I think it would be better if the Shortcut leads to the Switcher directly, or if switching account is made possible in the settings menu. This way it saves one step from navigating to the Switcher, and makes the shortcut more valuable.

**Comment by nyakowint** [comment]
You can open the switcher from the settings by pressing the profile looking button in the top right

Opening the actual switcher will be annoying java reflection and won't be added for a while

**Comment by nyakowint** [comment]
closing for now, read above comment
