### ISSUE TITLE
It doesn't show the usernames on connections (Unknownconnection)

### ISSUE THREAD

**Issue by Vansh1304** [ItzOnlyAnimal/AliuPlugins#27]
Hi, after installing that plugin (Unknownconnections), I'm not able to see usernames of anyone's connection (like the one in screenshot)
Is it possible to fix?
![Screenshot_2023-11-18-14-30-29-25_fa4ea8e8aeb69dcd3ab969e8fd3d4310](https://github.com/nyakowint/AliuPlugins/assets/132132057/9309531b-d66b-4816-835d-557c63c63eac)

**Comment by nyakowint** [comment]
Do you have the StreamerMode plugin? turn that off
Feel free to reopen if you still have this problem
