### ISSUE TITLE
Whyyyyyyy

### ISSUE THREAD

**Issue by omsenjalia** [ItzOnlyAnimal/AliuPlugins#4]
That free nitro one got me :/

![Screenshot_20211010-115857](https://user-images.githubusercontent.com/69719569/136685300-1a555739-b481-4ed1-9f9d-a13ceb7cc3fa.png)

**Comment by nyakowint** [comment]
ATTENTION CITIZEN! 市民请注意!

This is the Central Intelligentsia of the Chinese Communist Party. ()
您的 Internet 浏览器历史记录和活动引起了我们的注意。 
因此，您的个人资料中的 15 ( -15 Social Credits)  个社会积分将打折。:iloveccp: :iloveccp: :iloveccp: 🇨🇳 🇨🇳 
   🔴DO NOT DO THIS AGAIN!🔴  不要再这样做!  If you not hesitate, more Social Credits ( - Social Credits )will be subtracted from your profile, resulting in the subtraction of ration supplies. (由人民供应部重新分配 CCP)
You'll also be sent into a re-education camp in the Xinjiang Uyghur Autonomous Zone. :iloveccp: :iloveccp: :iloveccp: 🇨🇳 🇨🇳 
如果您毫不犹豫，更多的社会信用将从您的个人资料中打折，从而导致口粮供应减少。
您还将被送到新疆维吾尔自治区的再教育营。:iloveccp: :iloveccp: :iloveccp: 🇨🇳 🇨🇳 

为党争光! Glory to the PRC!

![image](https://user-images.githubusercontent.com/24845294/136685374-493adb7a-af49-4d61-9da4-3cb2c9add968.png)

https://user-images.githubusercontent.com/24845294/136685380-3583917a-1548-4cb6-aadb-0d34b204a84a.mp4

**Comment by omsenjalia** [comment]
![reverse-uno](https://user-images.githubusercontent.com/69719569/136701925-f53fe103-6aac-431c-9575-59a4ffdd7b4b.gif)
