### ISSUE TITLE
[Feature request] NoKyzas - setting to ignore bots messages (or specific users/channels)

### ISSUE THREAD

**Issue by MiincK** [ItzOnlyAnimal/AliuPlugins#5]
Best plugin I've seen ever but..
I have a bot that writes logs to some specific channels and the plugin makes all their messages lowercase (the case is sometimes important for me there). That'd be awesome to have either feature to ignore bots or feature to ignore specific channels/users
Thank you!

**Comment by nyakowint** [comment]
Will do soon

**Comment by nyakowint** [comment]
Latest update has a setting to ignore bots! 
Will probably make a feature for channel/user/server ids some time later
