### ISSUE TITLE
Quoter broken after 101.1 update

### ISSUE THREAD

**Issue by fym35** [ItzOnlyAnimal/AliuPlugins#6]
The quote button is just missing

**Comment by nyakowint** [comment]
make sure your base discord is 101.3, your aliucord is up to date, and quoter is the latest version (1.1.9)
If you're using a device with MiUi or some similar rom, it's because of pine (specifically, disabling the profile saver causes a crash)

**Comment by fym35** [comment]
It appears that the update of the plugin didn't show up in the updater for me but now i updated and it works just fine
